// <auto-generated />
namespace MvcSpAppWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class targetPrincipalNameaddedtomvcuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(targetPrincipalNameaddedtomvcuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201502061752414_target Principal Name added to mvc user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
